/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ButtonDemoRouteImport } from './routes/button-demo'
import { Route as IndexRouteImport } from './routes/index'

const ButtonDemoRoute = ButtonDemoRouteImport.update({
  id: '/button-demo',
  path: '/button-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button-demo': typeof ButtonDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button-demo': typeof ButtonDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button-demo': typeof ButtonDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/button-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/button-demo'
  id: '__root__' | '/' | '/button-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonDemoRoute: typeof ButtonDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/button-demo': {
      id: '/button-demo'
      path: '/button-demo'
      fullPath: '/button-demo'
      preLoaderRoute: typeof ButtonDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonDemoRoute: ButtonDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
